// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/dfs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // 例如 "127.0.0.1:50001"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	NextTargets   []string               `protobuf:"bytes,2,rep,name=next_targets,json=nextTargets,proto3" json:"next_targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Metadata) GetNextTargets() []string {
	if x != nil {
		return x.NextTargets
	}
	return nil
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 第一包先传元数据，后续再发内容
	//
	// Types that are valid to be assigned to Data:
	//
	//	*UploadRequest_Metadata
	//	*UploadRequest_Chunk
	Data          isUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *UploadRequest) GetData() isUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Data interface {
	isUploadRequest_Data()
}

type UploadRequest_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Metadata) isUploadRequest_Data() {}

func (*UploadRequest_Chunk) isUploadRequest_Data() {}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *UploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 请求存储位置
type AssignVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignVolumeRequest) Reset() {
	*x = AssignVolumeRequest{}
	mi := &file_api_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVolumeRequest) ProtoMessage() {}

func (x *AssignVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVolumeRequest.ProtoReflect.Descriptor instead.
func (*AssignVolumeRequest) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *AssignVolumeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AssignVolumeRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type AssignVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []string               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 上传凭证52
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignVolumeResponse) Reset() {
	*x = AssignVolumeResponse{}
	mi := &file_api_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignVolumeResponse) ProtoMessage() {}

func (x *AssignVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignVolumeResponse.ProtoReflect.Descriptor instead.
func (*AssignVolumeResponse) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *AssignVolumeResponse) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AssignVolumeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 请求文件位置
type FileLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLocationRequest) Reset() {
	*x = FileLocationRequest{}
	mi := &file_api_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLocationRequest) ProtoMessage() {}

func (x *FileLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLocationRequest.ProtoReflect.Descriptor instead.
func (*FileLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *FileLocationRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 只选出一个地址返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLocationResponse) Reset() {
	*x = FileLocationResponse{}
	mi := &file_api_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLocationResponse) ProtoMessage() {}

func (x *FileLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLocationResponse.ProtoReflect.Descriptor instead.
func (*FileLocationResponse) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *FileLocationResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 请求下载文件，和 volume 交互
type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_api_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_api_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_api_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_api_dfs_proto protoreflect.FileDescriptor

const file_api_dfs_proto_rawDesc = "" +
	"\n" +
	"\rapi/dfs.proto\x12\x03api\"D\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\bMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fnext_targets\x18\x02 \x03(\tR\vnextTargets\"\\\n" +
	"\rUploadRequest\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"C\n" +
	"\x0eUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"N\n" +
	"\x13AssignVolumeRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\"F\n" +
	"\x14AssignVolumeResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"1\n" +
	"\x13FileLocationRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"0\n" +
	"\x14FileLocationResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x0fDownloadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\",\n" +
	"\x10DownloadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent2\xd9\x01\n" +
	"\rMasterService\x12;\n" +
	"\fRegisterNode\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\x12C\n" +
	"\fAssignVolume\x12\x18.api.AssignVolumeRequest\x1a\x19.api.AssignVolumeResponse\x12F\n" +
	"\x0fGetFileLocation\x12\x18.api.FileLocationRequest\x1a\x19.api.FileLocationResponse2\x87\x01\n" +
	"\rVolumeService\x127\n" +
	"\n" +
	"UploadFile\x12\x12.api.UploadRequest\x1a\x13.api.UploadResponse(\x01\x12=\n" +
	"\fDownloadFile\x12\x14.api.DownloadRequest\x1a\x15.api.DownloadResponse0\x01B$Z\"github.com/calendar0917/go-dfs/apib\x06proto3"

var (
	file_api_dfs_proto_rawDescOnce sync.Once
	file_api_dfs_proto_rawDescData []byte
)

func file_api_dfs_proto_rawDescGZIP() []byte {
	file_api_dfs_proto_rawDescOnce.Do(func() {
		file_api_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dfs_proto_rawDesc), len(file_api_dfs_proto_rawDesc)))
	})
	return file_api_dfs_proto_rawDescData
}

var file_api_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_dfs_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: api.RegisterRequest
	(*RegisterResponse)(nil),     // 1: api.RegisterResponse
	(*Metadata)(nil),             // 2: api.Metadata
	(*UploadRequest)(nil),        // 3: api.UploadRequest
	(*UploadResponse)(nil),       // 4: api.UploadResponse
	(*AssignVolumeRequest)(nil),  // 5: api.AssignVolumeRequest
	(*AssignVolumeResponse)(nil), // 6: api.AssignVolumeResponse
	(*FileLocationRequest)(nil),  // 7: api.FileLocationRequest
	(*FileLocationResponse)(nil), // 8: api.FileLocationResponse
	(*DownloadRequest)(nil),      // 9: api.DownloadRequest
	(*DownloadResponse)(nil),     // 10: api.DownloadResponse
}
var file_api_dfs_proto_depIdxs = []int32{
	2,  // 0: api.UploadRequest.metadata:type_name -> api.Metadata
	0,  // 1: api.MasterService.RegisterNode:input_type -> api.RegisterRequest
	5,  // 2: api.MasterService.AssignVolume:input_type -> api.AssignVolumeRequest
	7,  // 3: api.MasterService.GetFileLocation:input_type -> api.FileLocationRequest
	3,  // 4: api.VolumeService.UploadFile:input_type -> api.UploadRequest
	9,  // 5: api.VolumeService.DownloadFile:input_type -> api.DownloadRequest
	1,  // 6: api.MasterService.RegisterNode:output_type -> api.RegisterResponse
	6,  // 7: api.MasterService.AssignVolume:output_type -> api.AssignVolumeResponse
	8,  // 8: api.MasterService.GetFileLocation:output_type -> api.FileLocationResponse
	4,  // 9: api.VolumeService.UploadFile:output_type -> api.UploadResponse
	10, // 10: api.VolumeService.DownloadFile:output_type -> api.DownloadResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_dfs_proto_init() }
func file_api_dfs_proto_init() {
	if File_api_dfs_proto != nil {
		return
	}
	file_api_dfs_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadRequest_Metadata)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dfs_proto_rawDesc), len(file_api_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_dfs_proto_goTypes,
		DependencyIndexes: file_api_dfs_proto_depIdxs,
		MessageInfos:      file_api_dfs_proto_msgTypes,
	}.Build()
	File_api_dfs_proto = out.File
	file_api_dfs_proto_goTypes = nil
	file_api_dfs_proto_depIdxs = nil
}
